<?php

use App\Models\Multitenancy\MultitenancyHelper;
use App\Modules\Form\Models\Exhibits;
use Illuminate\Database\Seeder;

class ExhibitsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run($clientId = 1)
    {
        MultitenancyHelper::run(function($client) {
            $exhibits = [
                [
                    'id'             => 1,
                    'code'           => 'EX-1',
                    'name'           => 'exhibit1',
                    'description'    => 'Underwriting agreement',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 2,
                    'code'           => 'EX-2',
                    'name'           => 'exhibit2',
                    'description'    => 'Plan of acquisition, reorganization, arrangement, liquidation or succession',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 3,
                    'code'           => 'EX-3(i)',
                    'name'           => 'exhibit3i',
                    'description'    => '(i) Articles of incorporation',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 4,
                    'code'           => 'EX-3(ii)',
                    'name'           => 'exhibit3ii',
                    'description'    => '(ii) Bylaws',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 5,
                    'code'           => 'EX-4',
                    'name'           => 'exhibit4',
                    'description'    => 'Instruments defining the rights of security holders, including indentures',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 6,
                    'code'           => 'EX-5',
                    'name'           => 'exhibit5',
                    'description'    => 'Opinion re legality',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 7,
                    'code'           => 'EX-7',
                    'name'           => 'exhibit7',
                    'description'    => 'Correspondence from an independent accountant regarding non-reliance on a previously issued audit report or completed interim review',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 8,
                    'code'           => 'EX-8',
                    'name'           => 'exhibit8',
                    'description'    => 'Opinion re tax matters',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 9,
                    'code'           => 'EX-9',
                    'name'           => 'exhibit9',
                    'description'    => 'Voting trust agreement',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 10,
                    'code'           => 'EX-10',
                    'name'           => 'exhibit10',
                    'description'    => 'Material contracts',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 11,
                    'code'           => 'EX-11',
                    'name'           => 'exhibit11',
                    'description'    => 'Statement re computation of per share earnings',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 12,
                    'code'           => 'EX-12',
                    'name'           => 'exhibit12',
                    'description'    => 'Statements re computation of ratios',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 13,
                    'code'           => 'EX-13',
                    'name'           => 'exhibit13',
                    'description'    => 'Annual report to security holders, Form 10-Q or quarterly report to security holders 3',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 14,
                    'code'           => 'EX-14',
                    'name'           => 'exhibit14',
                    'description'    => 'Code of Ethics',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 15,
                    'code'           => 'EX-15',
                    'name'           => 'exhibit15',
                    'description'    => 'Letter re unaudited interim financial information',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 16,
                    'code'           => 'EX-16',
                    'name'           => 'exhibit16',
                    'description'    => 'Letter re change in certifying accountant 4',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 17,
                    'code'           => 'EX-17',
                    'name'           => 'exhibit17',
                    'description'    => 'Correspondence on departure of director',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 18,
                    'code'           => 'EX-18',
                    'name'           => 'exhibit18',
                    'description'    => 'Letter re change in accounting principles',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 19,
                    'code'           => 'EX-19',
                    'name'           => 'exhibit19',
                    'description'    => 'Report furnished to security holders',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 20,
                    'code'           => 'EX-20',
                    'name'           => 'exhibit20',
                    'description'    => 'Other documents or statements to security holders',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 21,
                    'code'           => 'EX-21',
                    'name'           => 'exhibit21',
                    'description'    => 'Subsidiaries of the registrant',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 22,
                    'code'           => 'EX-22',
                    'name'           => 'exhibit22',
                    'description'    => 'Published report regarding matters submitted to vote of security holders',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 23,
                    'code'           => 'EX-23',
                    'name'           => 'exhibit23',
                    'description'    => 'Consents of experts and counsel',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 24,
                    'code'           => 'EX-24',
                    'name'           => 'exhibit24',
                    'description'    => 'Power of attorney',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 25,
                    'code'           => 'EX-25',
                    'name'           => 'exhibit25',
                    'description'    => 'Statement of eligibility of trustee',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 26,
                    'code'           => 'EX-26',
                    'name'           => 'exhibit26',
                    'description'    => 'Invitation for competitive bids',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 27,
                    'code'           => 'EX-31(i)',
                    'name'           => 'exhibit31i',
                    'description'    => '(i) Rule 13a-14(a)/15d-14(a) Certifications',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 28,
                    'code'           => 'EX-31(ii)',
                    'name'           => 'exhibit31ii',
                    'description'    => '(ii) Rule 13a-14/15d-14 Certification',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 29,
                    'code'           => 'EX-32',
                    'name'           => 'exhibit32',
                    'description'    => 'Section 1350 Certifications 6',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 30,
                    'code'           => 'EX-33',
                    'name'           => 'exhibit33',
                    'description'    => 'Report on assessment of compliance with servicing criteria for asset-backed issuers',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 31,
                    'code'           => 'EX-34',
                    'name'           => 'exhibit34',
                    'description'    => 'Attestation report on assessment of compliance with servicing criteria for asset-backed securities',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 32,
                    'code'           => 'EX-35',
                    'name'           => 'exhibit35',
                    'description'    => 'Servicer compliance statement',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 33,
                    'code'           => 'EX-36',
                    'name'           => 'exhibit36',
                    'description'    => 'Depositor Certification for shelf offerings of asset-backed securities',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 34,
                    'code'           => 'EX-95',
                    'name'           => 'exhibit95',
                    'description'    => 'Mine Safety Disclosure Exhibit',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 35,
                    'code'           => 'EX-99',
                    'name'           => 'exhibit99',
                    'description'    => 'Additional exhibits',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 36,
                    'code'           => 'EX-100',
                    'name'           => 'exhibit100',
                    'description'    => 'XBRL-Related Documents',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 37,
                    'code'           => 'EX-101',
                    'name'           => 'exhibit101',
                    'description'    => 'Interactive Data File',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 38,
                    'code'           => 'EX-102',
                    'name'           => 'exhibit102',
                    'description'    => 'Asset Data File',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 39,
                    'code'           => 'EX-103',
                    'name'           => 'exhibit103',
                    'description'    => 'Asset Related Documents',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 40,
                    'code'           => 'EX-106',
                    'name'           => 'exhibit106',
                    'description'    => 'Static Pool PDF',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 41,
                    'code'           => 'EX-96',
                    'name'           => 'exhibit96',
                    'description'    => 'Technical Report Summary',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
                [
                    'id'             => 42,
                    'code'           => 'EX-104',
                    'name'           => 'exhibit104',
                    'description'    => 'Cover Page Interactive Data File',
                    'created_at'     => '2019-09-30 16:27:42',
                    'updated_at'     => '2019-09-30 16:27:42',
                    'deleted_at'     => null,
                ],
            ];

            Exhibits::insert($exhibits);
        }, $clientId);
    }
}
